// Class automatically generated by Dev-C++ New Class wizard

#ifndef HISCORE_H
#define HISCORE_H
#include "constantes.h"

using namespace std;
 
class HiScore
{
	public:
		HiScore();
		~HiScore();
        int LeePuntos (int Number);
		const char *LeeNombre (int Number);
		void GrabaPuntos (int score, int Number);
		void GrabaNombre (char *name, int Number);
		int Save();
	private:
            char Valid;
            char Nombre[10][10];
            int Score[10], n;
};

#endif
