// Class automatically generated by Dev-C++ New Class wizard

#ifndef MENSAJES_H
#define MENSAJES_H

#include "constantes.h"
#include "configuracion.h"

class Mensajes
{
	public:
		Mensajes();
		~Mensajes();
		const char*  Leer (int NMensaje);
	private:
            char **Espanol, **English, **Asturianu, **Galego, **Catala;
            int Numero, Long, Idioma;
};

#endif // MENSAJES_H
