// Class automatically generated by Dev-C++ New Class wizard

#ifndef OBSTACULO_H
#define OBSTACULO_H

#include "sprite.h" // inheriting class's header file
#include "hardware.h"
#include "sprmanager.h"

class Obstaculo : public Sprite
{
	public:
		Obstaculo(int xo, int yo, int Tip);
		~Obstaculo();
		Obstaculo* VerSiguiente();
		void GrabarSiguiente (Obstaculo* Pointer);
		void Pasa ();
		bool VerPasado ();
		void rDibuja (int YInd, int Margen);
		void rBorra (int YInd, int Margen);
	private:
        Obstaculo *Siguiente;
        bool Pasado;
};

#endif // OBSTACULO_H
